#!/bin/bash

set -e

for i in solution.py test.py
do
  if ! test -f $i
  then
    echo "No solution.py"
    exit -1
  fi
done

echo "--- Running test.py ---"
if ! .test/timeout -t 60 python test.py >/dev/null
then
  echo "Running test.py failed"
  exit -2
fi

FAIL=""
echo "--- Running Tests ---"
for i in $(ls .test/test*.py)
do
	if ! .test/timeout -t 60 python $i
	then
		FAIL="$FAIL $i"
		echo "-> Failed"
	else
		echo "-> Passed"
	fi
done

if ! test -z "$FAIL"
then
	echo "Some tests failed."
	exit -3
fi
